spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bdfiap?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fiap}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:@Fiap2tds2023}
app.webhook.url=${APP_WEBHOOK_URL:https://fiapcom.webhook.office.com/webhookb2/890fd583-8024-46c4-a7fc-d9b021ce58ef@11dbbfe2-89b8-4549-be10-cec364e59551/IncomingWebhook/8c3ac7ddd96d4ff09272d58e27ea27bd/ce7e4666-ff8d-4fdc-ab27-eb2a0c59fb03/V2EMwwKJ5fZqK3pnQVO5tuKSyfADpN0ImxVt_JvNd0HE41}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
